name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Figure out a tag
      run: echo "TAG=$(date '+%Y%m%d-%H%M')" >> $GITHUB_ENV
    - name: Build and push Docker image
      uses: docker/build-push-action@v2.7.0
      with:
        context: .
        push: true
        tags: teyras/fio2gsheets:${{ env.TAG }}
